---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: local
    hooks:
      - id: check-json-in-config
        name: Check JSON files are in pre-commit-config.yaml
        entry: .cicd/check-json-in-config.py
        language: python
        types: [json]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
        args: [--assume-in-merge]
      - id: check-yaml
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.36.0
    hooks:
      - id: check-github-workflows
        name: Check GitHub workflows with check-jsonschema
        args: ["--verbose"]
      - id: check-renovate
        name: Check Renovate config with check-jsonschema
        additional_dependencies:
          # renovate: datasource=pypi
          - json5==0.13.0
        args: ["--verbose"]
  - repo: https://github.com/biomejs/pre-commit
    rev: v2.3.11
    hooks:
      - id: biome-check
        name: Check JavaScript with biome
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
        name: Check shell scripts with shellcheck
  - repo: https://github.com/renovatebot/pre-commit-hooks
    rev: 42.83.1
    hooks:
      - id: renovate-config-validator
        name: Check Renovate config with renovate-config-validator
        files: |
          (?x)(
               (^|/).?renovate(?:rc)?(?:\.json5?)?$|
               default.json|
               github-actions.json|
               groupByManager.json|
               package-sls.json|
               pre-commit.json|
               weekends.json|
               (?!)
          )$
