---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
        args: [--assume-in-merge]
      - id: check-yaml
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.29.4
    hooks:
      - id: check-github-workflows
        name: Check GitHub workflows with check-jsonschema
        args: ["--verbose"]
      - id: check-renovate
        name: Check Renovate config with check-jsonschema
        additional_dependencies:
          # renovate: datasource=pypi
          - json5==0.9.28
        args: ["--verbose"]
